name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key PMAK-6481c4f884f9ec0fcdb04e02-0101e0e89965a7b05a282afec77fb13cac
      - name: Run API tests
        run: |
          # Lint your API using Postman CLI
          postman api lint 44147a71-dbb1-4be3-9393-8e72dfbf65a5 --integration-id 142039
